### PR TITLE
Logout functionality working & app is conditionally rendering Home, List, Add Item fixes 

### LINKED ISSUE #21: Conditionally render Add Item and List pages
If the local storage contains no tokens, in other words if there is no list to add items to, the navlinks to `/add`and `/list` pages should be disabled.

Now it looks like this: no token, but links redirecting to Add Item, causing a confusing situation for the user when it is impossible to add anything to the list. See screenshot:
Screen Shot 2022-07-22 at 7 44 13 PM

### LINKED ISSUE #30: Render <Home/> conditionally
As a user, when I am 'logged in' (ie, when I have a token saved in storage), I should not see the <Home/> component.

### LINKED ISSUE #31: 'Log Out' feature
As a user, when I am 'logged in' (ie, when I have a token saved in storage), I should be able to 'log out' (ie, have my token deleted in local storage). 

With this feature, when a user clicks 'log out' (when their token is deleted from local storage), they should be sent back to `<Home/>`.

### PR DESCRIPTION
**Pull request by michellerenehey**
## Description

This PR adds a new feature: a user can log out! Logging out deletes the token in local storage, resets the token locally (to blank), and redirects a user to the `<Home/>` component. 

Additionally, I have added a users's `list name` (ie `listToken`) on the front-end, with a double-check alert before logging out. This is something we discussed in sync. 

During development a bug was discovered: we had a useEffect that was managing redirects (based on whether a user already had a token), and it was not allowing any redirects to or from home. I solved this by refactoring this logic out of a useEffect and into the `<Layout/>` component. 

With these changes, the fixes of conditionally rendering `Home`, `Link`, and `Add Item` are now fixed. 

## Related Issue
Closes #31 & Closes #30 & Closes #21 

## Acceptance Criteria
- moved basic functionality to the root component so that we can more easily manipulate state
- refactored layout to handle showing `NavLinks` based on `listToken`
- included `listToken` name in `List` component
- added a `logout` function, with an alert warning a user of logging out

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓   | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|  ✓   | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before
Home component before updates

List component before updates

### After

1. An existing token, you see the logout button & the name of the list. Note that you also do not see `Home` NavLink. 
List component after changes

2.  The alert a user sees when they click log out:
Log out alert

3. A user is redirected to Home, where you do not see `List` or `Add Item` NavLinks.
Home screen after log out

## Testing Steps / QA Criteria

1. Checkout `MN-log-out` for the latest changes on your local computer and `git pull`, then `npm start`.
2. If you don't have a list, create one. 
3. On the `List` component, notice the name of the list showing & a logout button. 
4. Click 'log out' 
5. Notice you are redirected to the `Home` component. 
6. Now, create a list then close the browser. Restart your local host, and notice that, with a token in localStorage, you are still brought to the `List` component.

### CODE REVIEW

File: src/App.jsx [hunk 1]
```diff
@@ -60,9 +60,20 @@ export function App() {
 		// eslint-disable-next-line react-hooks/exhaustive-deps
 	}, [listToken]);
 
+	function logOut() {
+		const confirm = window.confirm(
+			`If you're ready to log out, make sure to write down your list name before you click ok! It is ${listToken}`,
```
Comment (Trevor-Rezac) [inline src/App.jsx:65]: I really like this reminder/confirmation before logout! My only suggestion would be to add quotes, single or double, around the list token. I think it helps distinguish the token from the rest of the text a little easier, kind of similar to how it's a different color on the List component.

File: src/views/List.jsx [hunk 2]
```diff
@@ -77,12 +77,18 @@ export function List({ data, listToken, loading }) {
...
 	return (
 		<div className="list-container">
 			{loading ? (
 				<p>Your list is loading...</p>
 			) : (
 				<>
+					<button onClick={logOut}>Log Out</button>
+					<p>
+						Your list name is{' '}
+						<span style={{ color: 'salmon' }}>{listToken}</span>.
```
Comment (Trevor-Rezac) [inline src/views/List.jsx:90]: I really like rendering this a different color! Good thinking and easy way to make the token easy to spot.

File: src/views/Layout.jsx [hunk 3]
```diff
@@ -21,15 +21,21 @@ export function Layout() {
...
-					<NavLink to="/" className="Nav-link">
-						Home
-					</NavLink>
-					<NavLink to="/list" className="Nav-link">
-						List
-					</NavLink>
-					<NavLink to="/add-item" className="Nav-link">
-						Add Item
-					</NavLink>
+					{!listToken && (
```
Comment (Trevor-Rezac) [inline src/views/Layout.jsx:24]: Just purely out of curiosity, is there any reason why you chose to do `&&` here and on line 29, instead of making this one ternary?

**Review by Trevor-Rezac — APPROVED** [review]
Everything looks great and seems to work as intended! I added a few non-blocking comments and suggestions! Otherwise, I'm approving this PR! Nice work Michelle!

File: src/App.jsx (hunk 1 above)
Comment (N-Zubko) [reply src/App.jsx:65]: I agree with @Trevor-Rezac on additional highlighting the list name, may be make it italic or bold if the window.confirm allows it?

Comment (N-Zubko) [reply src/App.jsx:65]: and I like the notification part, because we care

File: src/App.jsx [hunk 4]
```diff
@@ -60,9 +60,20 @@ export function App() {
...
+		);
+		if (confirm) {
+			localStorage.clear();
```
Comment (N-Zubko) [inline src/App.jsx:68]: I like the progress - we learned about the window.confirm in one of the previous tickets and now you know the structure and are already applying it in a different place

File: src/views/Home.jsx [hunk 5]
```diff
@@ -28,30 +22,36 @@ export function Home({ handleClick, listToken, setListToken }) {
 
 	return (
 		<div className="Home">
-			<button onClick={handleClick}>Create New List</button>
+			{listToken ? (
+				navigateTo('/list')
```
Comment (N-Zubko) [inline src/views/Home.jsx:26]: Nice!

**Review by N-Zubko — APPROVED** [review]
Great job on completing this big issue single-handedly! I like that beside the logging out function, the app now displays the list name on the top and notifies when the user is about to exit the list - very comprehensentive approach!

File: src/App.jsx (hunk 1 above)
Comment (michellerenehey) [reply src/App.jsx:65]: Oh good call! I have added quotes around it. Unfortunately it looks like window.confirm can't be styled on it's own.

File: src/views/List.jsx (hunk 2 above)
Comment (michellerenehey) [reply src/views/List.jsx:90]: ✨  thank you! ✨

File: src/views/Layout.jsx (hunk 3 above)
Comment (michellerenehey) [reply src/views/Layout.jsx:24]: I hadn't really thought of using a ternary, tbh! I started with JUST the `!listToken` section (having only the <Home/> NavLink show if `!listToken`), and after that was built I added the opposite.

File: src/views/Layout.jsx [hunk 6]
```diff
@@ -21,15 +21,21 @@ export function Layout() {
...
+						<NavLink to="/" className="Nav-link">
+							Home
+						</NavLink>
+					)}
+					{listToken && (
```
Comment (lindseyindev) [inline src/views/Layout.jsx:29]: love this functionality!

File: src/views/Home.jsx [hunk 7]
```diff
@@ -8,12 +8,6 @@ export function Home({ handleClick, listToken, setListToken }) {
 	const [joinListName, setJoinListName] = useState('');
 	const [error, setError] = useState(false);
 
-	useEffect(() => {
```
Comment (lindseyindev) [inline src/views/Home.jsx:11]: great work on solving the behavior with React, there were a lot of moving parts to figure out in the conditional render part!

**Review by lindseyindev — APPROVED** [review]
Works great and looks great! Approving for shipping to prod! Really impressive work Michelle!

File: src/views/Home.jsx (hunk 7 above)
Comment (michellerenehey) [reply src/views/Home.jsx:11]: 😅 truly! thank you, @lindseyindev!
